// source: proto/cnspb/tradesummary.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_type_date_pb = require('../../google/type/date_pb.js');
goog.object.extend(proto, google_type_date_pb);
goog.exportSymbol('proto.cnspb.ListTradeSummaryRequest', null, global);
goog.exportSymbol('proto.cnspb.ListTradeSummaryResponse', null, global);
goog.exportSymbol('proto.cnspb.TradeSummary', null, global);
goog.exportSymbol('proto.cnspb.UpdateTradeSummaryRequest', null, global);
goog.exportSymbol('proto.cnspb.UpdateTradeSummaryResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cnspb.TradeSummary = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cnspb.TradeSummary, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cnspb.TradeSummary.displayName = 'proto.cnspb.TradeSummary';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cnspb.ListTradeSummaryRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cnspb.ListTradeSummaryRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cnspb.ListTradeSummaryRequest.displayName = 'proto.cnspb.ListTradeSummaryRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cnspb.ListTradeSummaryResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.cnspb.ListTradeSummaryResponse.repeatedFields_, null);
};
goog.inherits(proto.cnspb.ListTradeSummaryResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cnspb.ListTradeSummaryResponse.displayName = 'proto.cnspb.ListTradeSummaryResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cnspb.UpdateTradeSummaryRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cnspb.UpdateTradeSummaryRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cnspb.UpdateTradeSummaryRequest.displayName = 'proto.cnspb.UpdateTradeSummaryRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cnspb.UpdateTradeSummaryResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cnspb.UpdateTradeSummaryResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cnspb.UpdateTradeSummaryResponse.displayName = 'proto.cnspb.UpdateTradeSummaryResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cnspb.TradeSummary.prototype.toObject = function(opt_includeInstance) {
  return proto.cnspb.TradeSummary.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cnspb.TradeSummary} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cnspb.TradeSummary.toObject = function(includeInstance, msg) {
  var f, obj = {
    tradeSummaryId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    settleDate: (f = msg.getSettleDate()) && google_type_date_pb.Date.toObject(includeInstance, f),
    symbol: jspb.Message.getFieldWithDefault(msg, 3, ""),
    cusip: jspb.Message.getFieldWithDefault(msg, 4, ""),
    symbolDescription: jspb.Message.getFieldWithDefault(msg, 5, ""),
    houseQty: jspb.Message.getFieldWithDefault(msg, 8, ""),
    streetQty: jspb.Message.getFieldWithDefault(msg, 9, ""),
    breakQty: jspb.Message.getFieldWithDefault(msg, 10, ""),
    houseValue: jspb.Message.getFieldWithDefault(msg, 11, ""),
    streetValue: jspb.Message.getFieldWithDefault(msg, 12, ""),
    breakValue: jspb.Message.getFieldWithDefault(msg, 13, ""),
    streetDirectlyBilled: jspb.Message.getFieldWithDefault(msg, 14, ""),
    note: jspb.Message.getFieldWithDefault(msg, 15, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cnspb.TradeSummary}
 */
proto.cnspb.TradeSummary.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cnspb.TradeSummary;
  return proto.cnspb.TradeSummary.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cnspb.TradeSummary} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cnspb.TradeSummary}
 */
proto.cnspb.TradeSummary.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setTradeSummaryId(value);
      break;
    case 2:
      var value = new google_type_date_pb.Date;
      reader.readMessage(value,google_type_date_pb.Date.deserializeBinaryFromReader);
      msg.setSettleDate(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setSymbol(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setCusip(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setSymbolDescription(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setHouseQty(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setStreetQty(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setBreakQty(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setHouseValue(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setStreetValue(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setBreakValue(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setStreetDirectlyBilled(value);
      break;
    case 15:
      var value = /** @type {string} */ (reader.readString());
      msg.setNote(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cnspb.TradeSummary.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cnspb.TradeSummary.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cnspb.TradeSummary} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cnspb.TradeSummary.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTradeSummaryId();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getSettleDate();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_type_date_pb.Date.serializeBinaryToWriter
    );
  }
  f = message.getSymbol();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getCusip();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getSymbolDescription();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getHouseQty();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getStreetQty();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getBreakQty();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getHouseValue();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getStreetValue();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
  f = message.getBreakValue();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getStreetDirectlyBilled();
  if (f.length > 0) {
    writer.writeString(
      14,
      f
    );
  }
  f = message.getNote();
  if (f.length > 0) {
    writer.writeString(
      15,
      f
    );
  }
};


/**
 * optional uint32 trade_summary_id = 1;
 * @return {number}
 */
proto.cnspb.TradeSummary.prototype.getTradeSummaryId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.cnspb.TradeSummary} returns this
 */
proto.cnspb.TradeSummary.prototype.setTradeSummaryId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional google.type.Date settle_date = 2;
 * @return {?proto.google.type.Date}
 */
proto.cnspb.TradeSummary.prototype.getSettleDate = function() {
  return /** @type{?proto.google.type.Date} */ (
    jspb.Message.getWrapperField(this, google_type_date_pb.Date, 2));
};


/**
 * @param {?proto.google.type.Date|undefined} value
 * @return {!proto.cnspb.TradeSummary} returns this
*/
proto.cnspb.TradeSummary.prototype.setSettleDate = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cnspb.TradeSummary} returns this
 */
proto.cnspb.TradeSummary.prototype.clearSettleDate = function() {
  return this.setSettleDate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cnspb.TradeSummary.prototype.hasSettleDate = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string symbol = 3;
 * @return {string}
 */
proto.cnspb.TradeSummary.prototype.getSymbol = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.cnspb.TradeSummary} returns this
 */
proto.cnspb.TradeSummary.prototype.setSymbol = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string cusip = 4;
 * @return {string}
 */
proto.cnspb.TradeSummary.prototype.getCusip = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.cnspb.TradeSummary} returns this
 */
proto.cnspb.TradeSummary.prototype.setCusip = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string symbol_description = 5;
 * @return {string}
 */
proto.cnspb.TradeSummary.prototype.getSymbolDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.cnspb.TradeSummary} returns this
 */
proto.cnspb.TradeSummary.prototype.setSymbolDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string house_qty = 8;
 * @return {string}
 */
proto.cnspb.TradeSummary.prototype.getHouseQty = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.cnspb.TradeSummary} returns this
 */
proto.cnspb.TradeSummary.prototype.setHouseQty = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string street_qty = 9;
 * @return {string}
 */
proto.cnspb.TradeSummary.prototype.getStreetQty = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.cnspb.TradeSummary} returns this
 */
proto.cnspb.TradeSummary.prototype.setStreetQty = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional string break_qty = 10;
 * @return {string}
 */
proto.cnspb.TradeSummary.prototype.getBreakQty = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.cnspb.TradeSummary} returns this
 */
proto.cnspb.TradeSummary.prototype.setBreakQty = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional string house_value = 11;
 * @return {string}
 */
proto.cnspb.TradeSummary.prototype.getHouseValue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.cnspb.TradeSummary} returns this
 */
proto.cnspb.TradeSummary.prototype.setHouseValue = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional string street_value = 12;
 * @return {string}
 */
proto.cnspb.TradeSummary.prototype.getStreetValue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/**
 * @param {string} value
 * @return {!proto.cnspb.TradeSummary} returns this
 */
proto.cnspb.TradeSummary.prototype.setStreetValue = function(value) {
  return jspb.Message.setProto3StringField(this, 12, value);
};


/**
 * optional string break_value = 13;
 * @return {string}
 */
proto.cnspb.TradeSummary.prototype.getBreakValue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/**
 * @param {string} value
 * @return {!proto.cnspb.TradeSummary} returns this
 */
proto.cnspb.TradeSummary.prototype.setBreakValue = function(value) {
  return jspb.Message.setProto3StringField(this, 13, value);
};


/**
 * optional string street_directly_billed = 14;
 * @return {string}
 */
proto.cnspb.TradeSummary.prototype.getStreetDirectlyBilled = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/**
 * @param {string} value
 * @return {!proto.cnspb.TradeSummary} returns this
 */
proto.cnspb.TradeSummary.prototype.setStreetDirectlyBilled = function(value) {
  return jspb.Message.setProto3StringField(this, 14, value);
};


/**
 * optional string note = 15;
 * @return {string}
 */
proto.cnspb.TradeSummary.prototype.getNote = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 15, ""));
};


/**
 * @param {string} value
 * @return {!proto.cnspb.TradeSummary} returns this
 */
proto.cnspb.TradeSummary.prototype.setNote = function(value) {
  return jspb.Message.setProto3StringField(this, 15, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cnspb.ListTradeSummaryRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.cnspb.ListTradeSummaryRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cnspb.ListTradeSummaryRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cnspb.ListTradeSummaryRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    settleDate: (f = msg.getSettleDate()) && google_type_date_pb.Date.toObject(includeInstance, f),
    symbol: jspb.Message.getFieldWithDefault(msg, 2, ""),
    cusip: jspb.Message.getFieldWithDefault(msg, 3, ""),
    symbolDescription: jspb.Message.getFieldWithDefault(msg, 4, ""),
    showBreakOnly: jspb.Message.getBooleanFieldWithDefault(msg, 5, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cnspb.ListTradeSummaryRequest}
 */
proto.cnspb.ListTradeSummaryRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cnspb.ListTradeSummaryRequest;
  return proto.cnspb.ListTradeSummaryRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cnspb.ListTradeSummaryRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cnspb.ListTradeSummaryRequest}
 */
proto.cnspb.ListTradeSummaryRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_type_date_pb.Date;
      reader.readMessage(value,google_type_date_pb.Date.deserializeBinaryFromReader);
      msg.setSettleDate(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSymbol(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setCusip(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setSymbolDescription(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setShowBreakOnly(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cnspb.ListTradeSummaryRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cnspb.ListTradeSummaryRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cnspb.ListTradeSummaryRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cnspb.ListTradeSummaryRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSettleDate();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_type_date_pb.Date.serializeBinaryToWriter
    );
  }
  f = message.getSymbol();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getCusip();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getSymbolDescription();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getShowBreakOnly();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
};


/**
 * optional google.type.Date settle_date = 1;
 * @return {?proto.google.type.Date}
 */
proto.cnspb.ListTradeSummaryRequest.prototype.getSettleDate = function() {
  return /** @type{?proto.google.type.Date} */ (
    jspb.Message.getWrapperField(this, google_type_date_pb.Date, 1));
};


/**
 * @param {?proto.google.type.Date|undefined} value
 * @return {!proto.cnspb.ListTradeSummaryRequest} returns this
*/
proto.cnspb.ListTradeSummaryRequest.prototype.setSettleDate = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cnspb.ListTradeSummaryRequest} returns this
 */
proto.cnspb.ListTradeSummaryRequest.prototype.clearSettleDate = function() {
  return this.setSettleDate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cnspb.ListTradeSummaryRequest.prototype.hasSettleDate = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string symbol = 2;
 * @return {string}
 */
proto.cnspb.ListTradeSummaryRequest.prototype.getSymbol = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.cnspb.ListTradeSummaryRequest} returns this
 */
proto.cnspb.ListTradeSummaryRequest.prototype.setSymbol = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string cusip = 3;
 * @return {string}
 */
proto.cnspb.ListTradeSummaryRequest.prototype.getCusip = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.cnspb.ListTradeSummaryRequest} returns this
 */
proto.cnspb.ListTradeSummaryRequest.prototype.setCusip = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string symbol_description = 4;
 * @return {string}
 */
proto.cnspb.ListTradeSummaryRequest.prototype.getSymbolDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.cnspb.ListTradeSummaryRequest} returns this
 */
proto.cnspb.ListTradeSummaryRequest.prototype.setSymbolDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional bool show_break_only = 5;
 * @return {boolean}
 */
proto.cnspb.ListTradeSummaryRequest.prototype.getShowBreakOnly = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.cnspb.ListTradeSummaryRequest} returns this
 */
proto.cnspb.ListTradeSummaryRequest.prototype.setShowBreakOnly = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.cnspb.ListTradeSummaryResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cnspb.ListTradeSummaryResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.cnspb.ListTradeSummaryResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cnspb.ListTradeSummaryResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cnspb.ListTradeSummaryResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    tradeSummarysList: jspb.Message.toObjectList(msg.getTradeSummarysList(),
    proto.cnspb.TradeSummary.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cnspb.ListTradeSummaryResponse}
 */
proto.cnspb.ListTradeSummaryResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cnspb.ListTradeSummaryResponse;
  return proto.cnspb.ListTradeSummaryResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cnspb.ListTradeSummaryResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cnspb.ListTradeSummaryResponse}
 */
proto.cnspb.ListTradeSummaryResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.cnspb.TradeSummary;
      reader.readMessage(value,proto.cnspb.TradeSummary.deserializeBinaryFromReader);
      msg.addTradeSummarys(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cnspb.ListTradeSummaryResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cnspb.ListTradeSummaryResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cnspb.ListTradeSummaryResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cnspb.ListTradeSummaryResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTradeSummarysList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.cnspb.TradeSummary.serializeBinaryToWriter
    );
  }
};


/**
 * repeated TradeSummary trade_summarys = 1;
 * @return {!Array<!proto.cnspb.TradeSummary>}
 */
proto.cnspb.ListTradeSummaryResponse.prototype.getTradeSummarysList = function() {
  return /** @type{!Array<!proto.cnspb.TradeSummary>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.cnspb.TradeSummary, 1));
};


/**
 * @param {!Array<!proto.cnspb.TradeSummary>} value
 * @return {!proto.cnspb.ListTradeSummaryResponse} returns this
*/
proto.cnspb.ListTradeSummaryResponse.prototype.setTradeSummarysList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.cnspb.TradeSummary=} opt_value
 * @param {number=} opt_index
 * @return {!proto.cnspb.TradeSummary}
 */
proto.cnspb.ListTradeSummaryResponse.prototype.addTradeSummarys = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.cnspb.TradeSummary, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.cnspb.ListTradeSummaryResponse} returns this
 */
proto.cnspb.ListTradeSummaryResponse.prototype.clearTradeSummarysList = function() {
  return this.setTradeSummarysList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cnspb.UpdateTradeSummaryRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.cnspb.UpdateTradeSummaryRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cnspb.UpdateTradeSummaryRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cnspb.UpdateTradeSummaryRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    tradeSummaryId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    note: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cnspb.UpdateTradeSummaryRequest}
 */
proto.cnspb.UpdateTradeSummaryRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cnspb.UpdateTradeSummaryRequest;
  return proto.cnspb.UpdateTradeSummaryRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cnspb.UpdateTradeSummaryRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cnspb.UpdateTradeSummaryRequest}
 */
proto.cnspb.UpdateTradeSummaryRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setTradeSummaryId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setNote(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cnspb.UpdateTradeSummaryRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cnspb.UpdateTradeSummaryRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cnspb.UpdateTradeSummaryRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cnspb.UpdateTradeSummaryRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTradeSummaryId();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getNote();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional uint32 trade_summary_id = 1;
 * @return {number}
 */
proto.cnspb.UpdateTradeSummaryRequest.prototype.getTradeSummaryId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.cnspb.UpdateTradeSummaryRequest} returns this
 */
proto.cnspb.UpdateTradeSummaryRequest.prototype.setTradeSummaryId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string note = 2;
 * @return {string}
 */
proto.cnspb.UpdateTradeSummaryRequest.prototype.getNote = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.cnspb.UpdateTradeSummaryRequest} returns this
 */
proto.cnspb.UpdateTradeSummaryRequest.prototype.setNote = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cnspb.UpdateTradeSummaryResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.cnspb.UpdateTradeSummaryResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cnspb.UpdateTradeSummaryResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cnspb.UpdateTradeSummaryResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    tradeSummary: (f = msg.getTradeSummary()) && proto.cnspb.TradeSummary.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cnspb.UpdateTradeSummaryResponse}
 */
proto.cnspb.UpdateTradeSummaryResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cnspb.UpdateTradeSummaryResponse;
  return proto.cnspb.UpdateTradeSummaryResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cnspb.UpdateTradeSummaryResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cnspb.UpdateTradeSummaryResponse}
 */
proto.cnspb.UpdateTradeSummaryResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.cnspb.TradeSummary;
      reader.readMessage(value,proto.cnspb.TradeSummary.deserializeBinaryFromReader);
      msg.setTradeSummary(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cnspb.UpdateTradeSummaryResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cnspb.UpdateTradeSummaryResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cnspb.UpdateTradeSummaryResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cnspb.UpdateTradeSummaryResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTradeSummary();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.cnspb.TradeSummary.serializeBinaryToWriter
    );
  }
};


/**
 * optional TradeSummary trade_summary = 1;
 * @return {?proto.cnspb.TradeSummary}
 */
proto.cnspb.UpdateTradeSummaryResponse.prototype.getTradeSummary = function() {
  return /** @type{?proto.cnspb.TradeSummary} */ (
    jspb.Message.getWrapperField(this, proto.cnspb.TradeSummary, 1));
};


/**
 * @param {?proto.cnspb.TradeSummary|undefined} value
 * @return {!proto.cnspb.UpdateTradeSummaryResponse} returns this
*/
proto.cnspb.UpdateTradeSummaryResponse.prototype.setTradeSummary = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cnspb.UpdateTradeSummaryResponse} returns this
 */
proto.cnspb.UpdateTradeSummaryResponse.prototype.clearTradeSummary = function() {
  return this.setTradeSummary(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cnspb.UpdateTradeSummaryResponse.prototype.hasTradeSummary = function() {
  return jspb.Message.getField(this, 1) != null;
};


goog.object.extend(exports, proto.cnspb);
