// source: proto/assetpb/marginrate.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_type_date_pb = require('../../google/type/date_pb.js');
goog.object.extend(proto, google_type_date_pb);
goog.exportSymbol('proto.assetpb.CreateMarginRateResponse', null, global);
goog.exportSymbol('proto.assetpb.DeleteMarginRateRequest', null, global);
goog.exportSymbol('proto.assetpb.DeleteMarginRateResponse', null, global);
goog.exportSymbol('proto.assetpb.ListMarginRateResponse', null, global);
goog.exportSymbol('proto.assetpb.MarginRate', null, global);
goog.exportSymbol('proto.assetpb.UpdateMarginRateResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.assetpb.MarginRate = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.assetpb.MarginRate, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.assetpb.MarginRate.displayName = 'proto.assetpb.MarginRate';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.assetpb.ListMarginRateResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.assetpb.ListMarginRateResponse.repeatedFields_, null);
};
goog.inherits(proto.assetpb.ListMarginRateResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.assetpb.ListMarginRateResponse.displayName = 'proto.assetpb.ListMarginRateResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.assetpb.CreateMarginRateResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.assetpb.CreateMarginRateResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.assetpb.CreateMarginRateResponse.displayName = 'proto.assetpb.CreateMarginRateResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.assetpb.UpdateMarginRateResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.assetpb.UpdateMarginRateResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.assetpb.UpdateMarginRateResponse.displayName = 'proto.assetpb.UpdateMarginRateResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.assetpb.DeleteMarginRateRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.assetpb.DeleteMarginRateRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.assetpb.DeleteMarginRateRequest.displayName = 'proto.assetpb.DeleteMarginRateRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.assetpb.DeleteMarginRateResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.assetpb.DeleteMarginRateResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.assetpb.DeleteMarginRateResponse.displayName = 'proto.assetpb.DeleteMarginRateResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.assetpb.MarginRate.prototype.toObject = function(opt_includeInstance) {
  return proto.assetpb.MarginRate.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.assetpb.MarginRate} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.assetpb.MarginRate.toObject = function(includeInstance, msg) {
  var f, obj = {
    marginRateId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    fromDate: (f = msg.getFromDate()) && google_type_date_pb.Date.toObject(includeInstance, f),
    toDate: (f = msg.getToDate()) && google_type_date_pb.Date.toObject(includeInstance, f),
    requirementType: jspb.Message.getFieldWithDefault(msg, 4, ""),
    longRate: jspb.Message.getFieldWithDefault(msg, 5, ""),
    shortRate: jspb.Message.getFieldWithDefault(msg, 6, ""),
    status: jspb.Message.getFieldWithDefault(msg, 7, ""),
    symbol: jspb.Message.getFieldWithDefault(msg, 8, ""),
    originalCusip: jspb.Message.getFieldWithDefault(msg, 9, ""),
    cusip: jspb.Message.getFieldWithDefault(msg, 10, ""),
    symbolDescription: jspb.Message.getFieldWithDefault(msg, 11, ""),
    correspondent: jspb.Message.getFieldWithDefault(msg, 12, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.assetpb.MarginRate}
 */
proto.assetpb.MarginRate.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.assetpb.MarginRate;
  return proto.assetpb.MarginRate.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.assetpb.MarginRate} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.assetpb.MarginRate}
 */
proto.assetpb.MarginRate.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setMarginRateId(value);
      break;
    case 2:
      var value = new google_type_date_pb.Date;
      reader.readMessage(value,google_type_date_pb.Date.deserializeBinaryFromReader);
      msg.setFromDate(value);
      break;
    case 3:
      var value = new google_type_date_pb.Date;
      reader.readMessage(value,google_type_date_pb.Date.deserializeBinaryFromReader);
      msg.setToDate(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setRequirementType(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setLongRate(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setShortRate(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatus(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setSymbol(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setOriginalCusip(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setCusip(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setSymbolDescription(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setCorrespondent(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.assetpb.MarginRate.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.assetpb.MarginRate.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.assetpb.MarginRate} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.assetpb.MarginRate.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMarginRateId();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getFromDate();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_type_date_pb.Date.serializeBinaryToWriter
    );
  }
  f = message.getToDate();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_type_date_pb.Date.serializeBinaryToWriter
    );
  }
  f = message.getRequirementType();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getLongRate();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getShortRate();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getStatus();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getSymbol();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getOriginalCusip();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getCusip();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getSymbolDescription();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getCorrespondent();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
};


/**
 * optional uint32 margin_rate_id = 1;
 * @return {number}
 */
proto.assetpb.MarginRate.prototype.getMarginRateId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.assetpb.MarginRate} returns this
 */
proto.assetpb.MarginRate.prototype.setMarginRateId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional google.type.Date from_date = 2;
 * @return {?proto.google.type.Date}
 */
proto.assetpb.MarginRate.prototype.getFromDate = function() {
  return /** @type{?proto.google.type.Date} */ (
    jspb.Message.getWrapperField(this, google_type_date_pb.Date, 2));
};


/**
 * @param {?proto.google.type.Date|undefined} value
 * @return {!proto.assetpb.MarginRate} returns this
*/
proto.assetpb.MarginRate.prototype.setFromDate = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.assetpb.MarginRate} returns this
 */
proto.assetpb.MarginRate.prototype.clearFromDate = function() {
  return this.setFromDate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.assetpb.MarginRate.prototype.hasFromDate = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.type.Date to_date = 3;
 * @return {?proto.google.type.Date}
 */
proto.assetpb.MarginRate.prototype.getToDate = function() {
  return /** @type{?proto.google.type.Date} */ (
    jspb.Message.getWrapperField(this, google_type_date_pb.Date, 3));
};


/**
 * @param {?proto.google.type.Date|undefined} value
 * @return {!proto.assetpb.MarginRate} returns this
*/
proto.assetpb.MarginRate.prototype.setToDate = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.assetpb.MarginRate} returns this
 */
proto.assetpb.MarginRate.prototype.clearToDate = function() {
  return this.setToDate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.assetpb.MarginRate.prototype.hasToDate = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string requirement_type = 4;
 * @return {string}
 */
proto.assetpb.MarginRate.prototype.getRequirementType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.assetpb.MarginRate} returns this
 */
proto.assetpb.MarginRate.prototype.setRequirementType = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string long_rate = 5;
 * @return {string}
 */
proto.assetpb.MarginRate.prototype.getLongRate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.assetpb.MarginRate} returns this
 */
proto.assetpb.MarginRate.prototype.setLongRate = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string short_rate = 6;
 * @return {string}
 */
proto.assetpb.MarginRate.prototype.getShortRate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.assetpb.MarginRate} returns this
 */
proto.assetpb.MarginRate.prototype.setShortRate = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string status = 7;
 * @return {string}
 */
proto.assetpb.MarginRate.prototype.getStatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.assetpb.MarginRate} returns this
 */
proto.assetpb.MarginRate.prototype.setStatus = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string symbol = 8;
 * @return {string}
 */
proto.assetpb.MarginRate.prototype.getSymbol = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.assetpb.MarginRate} returns this
 */
proto.assetpb.MarginRate.prototype.setSymbol = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string original_cusip = 9;
 * @return {string}
 */
proto.assetpb.MarginRate.prototype.getOriginalCusip = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.assetpb.MarginRate} returns this
 */
proto.assetpb.MarginRate.prototype.setOriginalCusip = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional string cusip = 10;
 * @return {string}
 */
proto.assetpb.MarginRate.prototype.getCusip = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.assetpb.MarginRate} returns this
 */
proto.assetpb.MarginRate.prototype.setCusip = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional string symbol_description = 11;
 * @return {string}
 */
proto.assetpb.MarginRate.prototype.getSymbolDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.assetpb.MarginRate} returns this
 */
proto.assetpb.MarginRate.prototype.setSymbolDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional string correspondent = 12;
 * @return {string}
 */
proto.assetpb.MarginRate.prototype.getCorrespondent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/**
 * @param {string} value
 * @return {!proto.assetpb.MarginRate} returns this
 */
proto.assetpb.MarginRate.prototype.setCorrespondent = function(value) {
  return jspb.Message.setProto3StringField(this, 12, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.assetpb.ListMarginRateResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.assetpb.ListMarginRateResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.assetpb.ListMarginRateResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.assetpb.ListMarginRateResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.assetpb.ListMarginRateResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    marginRatesList: jspb.Message.toObjectList(msg.getMarginRatesList(),
    proto.assetpb.MarginRate.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.assetpb.ListMarginRateResponse}
 */
proto.assetpb.ListMarginRateResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.assetpb.ListMarginRateResponse;
  return proto.assetpb.ListMarginRateResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.assetpb.ListMarginRateResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.assetpb.ListMarginRateResponse}
 */
proto.assetpb.ListMarginRateResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.assetpb.MarginRate;
      reader.readMessage(value,proto.assetpb.MarginRate.deserializeBinaryFromReader);
      msg.addMarginRates(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.assetpb.ListMarginRateResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.assetpb.ListMarginRateResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.assetpb.ListMarginRateResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.assetpb.ListMarginRateResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMarginRatesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.assetpb.MarginRate.serializeBinaryToWriter
    );
  }
};


/**
 * repeated MarginRate margin_rates = 1;
 * @return {!Array<!proto.assetpb.MarginRate>}
 */
proto.assetpb.ListMarginRateResponse.prototype.getMarginRatesList = function() {
  return /** @type{!Array<!proto.assetpb.MarginRate>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.assetpb.MarginRate, 1));
};


/**
 * @param {!Array<!proto.assetpb.MarginRate>} value
 * @return {!proto.assetpb.ListMarginRateResponse} returns this
*/
proto.assetpb.ListMarginRateResponse.prototype.setMarginRatesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.assetpb.MarginRate=} opt_value
 * @param {number=} opt_index
 * @return {!proto.assetpb.MarginRate}
 */
proto.assetpb.ListMarginRateResponse.prototype.addMarginRates = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.assetpb.MarginRate, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.assetpb.ListMarginRateResponse} returns this
 */
proto.assetpb.ListMarginRateResponse.prototype.clearMarginRatesList = function() {
  return this.setMarginRatesList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.assetpb.CreateMarginRateResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.assetpb.CreateMarginRateResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.assetpb.CreateMarginRateResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.assetpb.CreateMarginRateResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    marginRate: (f = msg.getMarginRate()) && proto.assetpb.MarginRate.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.assetpb.CreateMarginRateResponse}
 */
proto.assetpb.CreateMarginRateResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.assetpb.CreateMarginRateResponse;
  return proto.assetpb.CreateMarginRateResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.assetpb.CreateMarginRateResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.assetpb.CreateMarginRateResponse}
 */
proto.assetpb.CreateMarginRateResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.assetpb.MarginRate;
      reader.readMessage(value,proto.assetpb.MarginRate.deserializeBinaryFromReader);
      msg.setMarginRate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.assetpb.CreateMarginRateResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.assetpb.CreateMarginRateResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.assetpb.CreateMarginRateResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.assetpb.CreateMarginRateResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMarginRate();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.assetpb.MarginRate.serializeBinaryToWriter
    );
  }
};


/**
 * optional MarginRate margin_rate = 1;
 * @return {?proto.assetpb.MarginRate}
 */
proto.assetpb.CreateMarginRateResponse.prototype.getMarginRate = function() {
  return /** @type{?proto.assetpb.MarginRate} */ (
    jspb.Message.getWrapperField(this, proto.assetpb.MarginRate, 1));
};


/**
 * @param {?proto.assetpb.MarginRate|undefined} value
 * @return {!proto.assetpb.CreateMarginRateResponse} returns this
*/
proto.assetpb.CreateMarginRateResponse.prototype.setMarginRate = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.assetpb.CreateMarginRateResponse} returns this
 */
proto.assetpb.CreateMarginRateResponse.prototype.clearMarginRate = function() {
  return this.setMarginRate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.assetpb.CreateMarginRateResponse.prototype.hasMarginRate = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.assetpb.UpdateMarginRateResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.assetpb.UpdateMarginRateResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.assetpb.UpdateMarginRateResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.assetpb.UpdateMarginRateResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    marginRate: (f = msg.getMarginRate()) && proto.assetpb.MarginRate.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.assetpb.UpdateMarginRateResponse}
 */
proto.assetpb.UpdateMarginRateResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.assetpb.UpdateMarginRateResponse;
  return proto.assetpb.UpdateMarginRateResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.assetpb.UpdateMarginRateResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.assetpb.UpdateMarginRateResponse}
 */
proto.assetpb.UpdateMarginRateResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.assetpb.MarginRate;
      reader.readMessage(value,proto.assetpb.MarginRate.deserializeBinaryFromReader);
      msg.setMarginRate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.assetpb.UpdateMarginRateResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.assetpb.UpdateMarginRateResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.assetpb.UpdateMarginRateResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.assetpb.UpdateMarginRateResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMarginRate();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.assetpb.MarginRate.serializeBinaryToWriter
    );
  }
};


/**
 * optional MarginRate margin_rate = 1;
 * @return {?proto.assetpb.MarginRate}
 */
proto.assetpb.UpdateMarginRateResponse.prototype.getMarginRate = function() {
  return /** @type{?proto.assetpb.MarginRate} */ (
    jspb.Message.getWrapperField(this, proto.assetpb.MarginRate, 1));
};


/**
 * @param {?proto.assetpb.MarginRate|undefined} value
 * @return {!proto.assetpb.UpdateMarginRateResponse} returns this
*/
proto.assetpb.UpdateMarginRateResponse.prototype.setMarginRate = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.assetpb.UpdateMarginRateResponse} returns this
 */
proto.assetpb.UpdateMarginRateResponse.prototype.clearMarginRate = function() {
  return this.setMarginRate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.assetpb.UpdateMarginRateResponse.prototype.hasMarginRate = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.assetpb.DeleteMarginRateRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.assetpb.DeleteMarginRateRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.assetpb.DeleteMarginRateRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.assetpb.DeleteMarginRateRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    marginRateId: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.assetpb.DeleteMarginRateRequest}
 */
proto.assetpb.DeleteMarginRateRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.assetpb.DeleteMarginRateRequest;
  return proto.assetpb.DeleteMarginRateRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.assetpb.DeleteMarginRateRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.assetpb.DeleteMarginRateRequest}
 */
proto.assetpb.DeleteMarginRateRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setMarginRateId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.assetpb.DeleteMarginRateRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.assetpb.DeleteMarginRateRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.assetpb.DeleteMarginRateRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.assetpb.DeleteMarginRateRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMarginRateId();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
};


/**
 * optional uint32 margin_rate_id = 1;
 * @return {number}
 */
proto.assetpb.DeleteMarginRateRequest.prototype.getMarginRateId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.assetpb.DeleteMarginRateRequest} returns this
 */
proto.assetpb.DeleteMarginRateRequest.prototype.setMarginRateId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.assetpb.DeleteMarginRateResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.assetpb.DeleteMarginRateResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.assetpb.DeleteMarginRateResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.assetpb.DeleteMarginRateResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    marginRate: (f = msg.getMarginRate()) && proto.assetpb.MarginRate.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.assetpb.DeleteMarginRateResponse}
 */
proto.assetpb.DeleteMarginRateResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.assetpb.DeleteMarginRateResponse;
  return proto.assetpb.DeleteMarginRateResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.assetpb.DeleteMarginRateResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.assetpb.DeleteMarginRateResponse}
 */
proto.assetpb.DeleteMarginRateResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.assetpb.MarginRate;
      reader.readMessage(value,proto.assetpb.MarginRate.deserializeBinaryFromReader);
      msg.setMarginRate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.assetpb.DeleteMarginRateResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.assetpb.DeleteMarginRateResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.assetpb.DeleteMarginRateResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.assetpb.DeleteMarginRateResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMarginRate();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.assetpb.MarginRate.serializeBinaryToWriter
    );
  }
};


/**
 * optional MarginRate margin_rate = 1;
 * @return {?proto.assetpb.MarginRate}
 */
proto.assetpb.DeleteMarginRateResponse.prototype.getMarginRate = function() {
  return /** @type{?proto.assetpb.MarginRate} */ (
    jspb.Message.getWrapperField(this, proto.assetpb.MarginRate, 1));
};


/**
 * @param {?proto.assetpb.MarginRate|undefined} value
 * @return {!proto.assetpb.DeleteMarginRateResponse} returns this
*/
proto.assetpb.DeleteMarginRateResponse.prototype.setMarginRate = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.assetpb.DeleteMarginRateResponse} returns this
 */
proto.assetpb.DeleteMarginRateResponse.prototype.clearMarginRate = function() {
  return this.setMarginRate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.assetpb.DeleteMarginRateResponse.prototype.hasMarginRate = function() {
  return jspb.Message.getField(this, 1) != null;
};


goog.object.extend(exports, proto.assetpb);
