// source: proto/apipb/client.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var google_type_date_pb = require('../../google/type/date_pb.js');
goog.object.extend(proto, google_type_date_pb);
goog.exportSymbol('proto.apipb.ApiClient', null, global);
goog.exportSymbol('proto.apipb.ListApiClientRequest', null, global);
goog.exportSymbol('proto.apipb.ListApiClientResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.apipb.ApiClient = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.apipb.ApiClient, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.apipb.ApiClient.displayName = 'proto.apipb.ApiClient';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.apipb.ListApiClientRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.apipb.ListApiClientRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.apipb.ListApiClientRequest.displayName = 'proto.apipb.ListApiClientRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.apipb.ListApiClientResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.apipb.ListApiClientResponse.repeatedFields_, null);
};
goog.inherits(proto.apipb.ListApiClientResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.apipb.ListApiClientResponse.displayName = 'proto.apipb.ListApiClientResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.apipb.ApiClient.prototype.toObject = function(opt_includeInstance) {
  return proto.apipb.ApiClient.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.apipb.ApiClient} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apipb.ApiClient.toObject = function(includeInstance, msg) {
  var f, obj = {
    clientId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    id: jspb.Message.getFieldWithDefault(msg, 2, ""),
    kycStatus: jspb.Message.getFieldWithDefault(msg, 3, ""),
    brokerAccountStatus: jspb.Message.getFieldWithDefault(msg, 4, ""),
    brokerAccountStatusReason: jspb.Message.getFieldWithDefault(msg, 5, ""),
    type: jspb.Message.getFieldWithDefault(msg, 6, ""),
    subType: jspb.Message.getFieldWithDefault(msg, 7, ""),
    brokerId: jspb.Message.getFieldWithDefault(msg, 8, ""),
    domicile: jspb.Message.getFieldWithDefault(msg, 9, ""),
    allowIlliquidInvestments: jspb.Message.getBooleanFieldWithDefault(msg, 10, false),
    accountLegalName: jspb.Message.getFieldWithDefault(msg, 11, ""),
    accreditation: jspb.Message.getFieldWithDefault(msg, 12, ""),
    primaryApplicationSignedOn: (f = msg.getPrimaryApplicationSignedOn()) && google_type_date_pb.Date.toObject(includeInstance, f),
    clearingInformation: jspb.Message.getFieldWithDefault(msg, 14, ""),
    dvpExemptions: jspb.Message.getFieldWithDefault(msg, 15, ""),
    dinoMigrationAccount: jspb.Message.getBooleanFieldWithDefault(msg, 16, false),
    migrationChanges: jspb.Message.getFieldWithDefault(msg, 17, ""),
    currentUserIsPrimary: jspb.Message.getBooleanFieldWithDefault(msg, 18, false),
    ownerId: jspb.Message.getFieldWithDefault(msg, 19, ""),
    firstName: jspb.Message.getFieldWithDefault(msg, 20, ""),
    middleName: jspb.Message.getFieldWithDefault(msg, 21, ""),
    email: jspb.Message.getFieldWithDefault(msg, 22, ""),
    lastName: jspb.Message.getFieldWithDefault(msg, 23, ""),
    birthDate: (f = msg.getBirthDate()) && google_type_date_pb.Date.toObject(includeInstance, f),
    citizenshipCountryCode: jspb.Message.getFieldWithDefault(msg, 25, ""),
    countryCode: jspb.Message.getFieldWithDefault(msg, 26, ""),
    tin: jspb.Message.getFieldWithDefault(msg, 27, ""),
    internationalTin: jspb.Message.getFieldWithDefault(msg, 28, ""),
    tinCountryCode: jspb.Message.getFieldWithDefault(msg, 29, ""),
    physicalStreet: jspb.Message.getFieldWithDefault(msg, 30, ""),
    physicalStreet2: jspb.Message.getFieldWithDefault(msg, 31, ""),
    physicalStreet3: jspb.Message.getFieldWithDefault(msg, 32, ""),
    physicalStreet4: jspb.Message.getFieldWithDefault(msg, 33, ""),
    physicalCity: jspb.Message.getFieldWithDefault(msg, 34, ""),
    physicalRegion: jspb.Message.getFieldWithDefault(msg, 35, ""),
    physicalPostalCode: jspb.Message.getFieldWithDefault(msg, 36, ""),
    physicalCountryCode: jspb.Message.getFieldWithDefault(msg, 37, ""),
    mailingStreet: jspb.Message.getFieldWithDefault(msg, 38, ""),
    mailingStreet2: jspb.Message.getFieldWithDefault(msg, 39, ""),
    mailingStreet3: jspb.Message.getFieldWithDefault(msg, 40, ""),
    mailingStreet4: jspb.Message.getFieldWithDefault(msg, 41, ""),
    mailingCity: jspb.Message.getFieldWithDefault(msg, 42, ""),
    mailingRegion: jspb.Message.getFieldWithDefault(msg, 43, ""),
    mailingPostalCode: jspb.Message.getFieldWithDefault(msg, 44, ""),
    mailingCountryCode: jspb.Message.getFieldWithDefault(msg, 45, ""),
    employmentStatusId: jspb.Message.getFieldWithDefault(msg, 46, ""),
    employmentStatusLabel: jspb.Message.getFieldWithDefault(msg, 47, ""),
    employmentEmployerName: jspb.Message.getFieldWithDefault(msg, 48, ""),
    employmentOccupation: jspb.Message.getFieldWithDefault(msg, 49, ""),
    investorPurposeId: jspb.Message.getFieldWithDefault(msg, 50, ""),
    investorPurposeLabel: jspb.Message.getFieldWithDefault(msg, 51, ""),
    investmentAllowIlliquidInvestments: jspb.Message.getBooleanFieldWithDefault(msg, 52, false),
    hasPublicDisclosure: jspb.Message.getBooleanFieldWithDefault(msg, 53, false),
    publicDisclosure: jspb.Message.getFieldWithDefault(msg, 54, ""),
    hasStockDisclosure: jspb.Message.getBooleanFieldWithDefault(msg, 55, false),
    stockDisclosureFirm: jspb.Message.getFieldWithDefault(msg, 56, ""),
    stockDisclosurePosition: jspb.Message.getFieldWithDefault(msg, 57, ""),
    customerAgreementsWebTermCondition: (f = msg.getCustomerAgreementsWebTermCondition()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    customerAgreementsDisclosureStatement: (f = msg.getCustomerAgreementsDisclosureStatement()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    customerAgreementsFeeSchedule: (f = msg.getCustomerAgreementsFeeSchedule()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    trustedContactFirstName: jspb.Message.getFieldWithDefault(msg, 61, ""),
    trustedContactLastName: jspb.Message.getFieldWithDefault(msg, 62, ""),
    trustedContactEmailAddress: jspb.Message.getFieldWithDefault(msg, 63, ""),
    trustedContactPhoneNumber: jspb.Message.getFieldWithDefault(msg, 64, ""),
    trustedContactAddressLine1: jspb.Message.getFieldWithDefault(msg, 65, ""),
    trustedContactAddressLine2: jspb.Message.getFieldWithDefault(msg, 66, ""),
    trustedContactCity: jspb.Message.getFieldWithDefault(msg, 67, ""),
    trustedContactRegion: jspb.Message.getFieldWithDefault(msg, 68, ""),
    trustedContactPostalCode: jspb.Message.getFieldWithDefault(msg, 69, ""),
    trustedContactCountry: jspb.Message.getFieldWithDefault(msg, 70, ""),
    trustedContactOptOut: jspb.Message.getBooleanFieldWithDefault(msg, 71, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.apipb.ApiClient}
 */
proto.apipb.ApiClient.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.apipb.ApiClient;
  return proto.apipb.ApiClient.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.apipb.ApiClient} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.apipb.ApiClient}
 */
proto.apipb.ApiClient.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setClientId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setKycStatus(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setBrokerAccountStatus(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setBrokerAccountStatusReason(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setType(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setSubType(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setBrokerId(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setDomicile(value);
      break;
    case 10:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAllowIlliquidInvestments(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setAccountLegalName(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setAccreditation(value);
      break;
    case 13:
      var value = new google_type_date_pb.Date;
      reader.readMessage(value,google_type_date_pb.Date.deserializeBinaryFromReader);
      msg.setPrimaryApplicationSignedOn(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setClearingInformation(value);
      break;
    case 15:
      var value = /** @type {string} */ (reader.readString());
      msg.setDvpExemptions(value);
      break;
    case 16:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setDinoMigrationAccount(value);
      break;
    case 17:
      var value = /** @type {string} */ (reader.readString());
      msg.setMigrationChanges(value);
      break;
    case 18:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setCurrentUserIsPrimary(value);
      break;
    case 19:
      var value = /** @type {string} */ (reader.readString());
      msg.setOwnerId(value);
      break;
    case 20:
      var value = /** @type {string} */ (reader.readString());
      msg.setFirstName(value);
      break;
    case 21:
      var value = /** @type {string} */ (reader.readString());
      msg.setMiddleName(value);
      break;
    case 22:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmail(value);
      break;
    case 23:
      var value = /** @type {string} */ (reader.readString());
      msg.setLastName(value);
      break;
    case 24:
      var value = new google_type_date_pb.Date;
      reader.readMessage(value,google_type_date_pb.Date.deserializeBinaryFromReader);
      msg.setBirthDate(value);
      break;
    case 25:
      var value = /** @type {string} */ (reader.readString());
      msg.setCitizenshipCountryCode(value);
      break;
    case 26:
      var value = /** @type {string} */ (reader.readString());
      msg.setCountryCode(value);
      break;
    case 27:
      var value = /** @type {string} */ (reader.readString());
      msg.setTin(value);
      break;
    case 28:
      var value = /** @type {string} */ (reader.readString());
      msg.setInternationalTin(value);
      break;
    case 29:
      var value = /** @type {string} */ (reader.readString());
      msg.setTinCountryCode(value);
      break;
    case 30:
      var value = /** @type {string} */ (reader.readString());
      msg.setPhysicalStreet(value);
      break;
    case 31:
      var value = /** @type {string} */ (reader.readString());
      msg.setPhysicalStreet2(value);
      break;
    case 32:
      var value = /** @type {string} */ (reader.readString());
      msg.setPhysicalStreet3(value);
      break;
    case 33:
      var value = /** @type {string} */ (reader.readString());
      msg.setPhysicalStreet4(value);
      break;
    case 34:
      var value = /** @type {string} */ (reader.readString());
      msg.setPhysicalCity(value);
      break;
    case 35:
      var value = /** @type {string} */ (reader.readString());
      msg.setPhysicalRegion(value);
      break;
    case 36:
      var value = /** @type {string} */ (reader.readString());
      msg.setPhysicalPostalCode(value);
      break;
    case 37:
      var value = /** @type {string} */ (reader.readString());
      msg.setPhysicalCountryCode(value);
      break;
    case 38:
      var value = /** @type {string} */ (reader.readString());
      msg.setMailingStreet(value);
      break;
    case 39:
      var value = /** @type {string} */ (reader.readString());
      msg.setMailingStreet2(value);
      break;
    case 40:
      var value = /** @type {string} */ (reader.readString());
      msg.setMailingStreet3(value);
      break;
    case 41:
      var value = /** @type {string} */ (reader.readString());
      msg.setMailingStreet4(value);
      break;
    case 42:
      var value = /** @type {string} */ (reader.readString());
      msg.setMailingCity(value);
      break;
    case 43:
      var value = /** @type {string} */ (reader.readString());
      msg.setMailingRegion(value);
      break;
    case 44:
      var value = /** @type {string} */ (reader.readString());
      msg.setMailingPostalCode(value);
      break;
    case 45:
      var value = /** @type {string} */ (reader.readString());
      msg.setMailingCountryCode(value);
      break;
    case 46:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmploymentStatusId(value);
      break;
    case 47:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmploymentStatusLabel(value);
      break;
    case 48:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmploymentEmployerName(value);
      break;
    case 49:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmploymentOccupation(value);
      break;
    case 50:
      var value = /** @type {string} */ (reader.readString());
      msg.setInvestorPurposeId(value);
      break;
    case 51:
      var value = /** @type {string} */ (reader.readString());
      msg.setInvestorPurposeLabel(value);
      break;
    case 52:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setInvestmentAllowIlliquidInvestments(value);
      break;
    case 53:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setHasPublicDisclosure(value);
      break;
    case 54:
      var value = /** @type {string} */ (reader.readString());
      msg.setPublicDisclosure(value);
      break;
    case 55:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setHasStockDisclosure(value);
      break;
    case 56:
      var value = /** @type {string} */ (reader.readString());
      msg.setStockDisclosureFirm(value);
      break;
    case 57:
      var value = /** @type {string} */ (reader.readString());
      msg.setStockDisclosurePosition(value);
      break;
    case 58:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCustomerAgreementsWebTermCondition(value);
      break;
    case 59:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCustomerAgreementsDisclosureStatement(value);
      break;
    case 60:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCustomerAgreementsFeeSchedule(value);
      break;
    case 61:
      var value = /** @type {string} */ (reader.readString());
      msg.setTrustedContactFirstName(value);
      break;
    case 62:
      var value = /** @type {string} */ (reader.readString());
      msg.setTrustedContactLastName(value);
      break;
    case 63:
      var value = /** @type {string} */ (reader.readString());
      msg.setTrustedContactEmailAddress(value);
      break;
    case 64:
      var value = /** @type {string} */ (reader.readString());
      msg.setTrustedContactPhoneNumber(value);
      break;
    case 65:
      var value = /** @type {string} */ (reader.readString());
      msg.setTrustedContactAddressLine1(value);
      break;
    case 66:
      var value = /** @type {string} */ (reader.readString());
      msg.setTrustedContactAddressLine2(value);
      break;
    case 67:
      var value = /** @type {string} */ (reader.readString());
      msg.setTrustedContactCity(value);
      break;
    case 68:
      var value = /** @type {string} */ (reader.readString());
      msg.setTrustedContactRegion(value);
      break;
    case 69:
      var value = /** @type {string} */ (reader.readString());
      msg.setTrustedContactPostalCode(value);
      break;
    case 70:
      var value = /** @type {string} */ (reader.readString());
      msg.setTrustedContactCountry(value);
      break;
    case 71:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setTrustedContactOptOut(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.apipb.ApiClient.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.apipb.ApiClient.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.apipb.ApiClient} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apipb.ApiClient.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getClientId();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getKycStatus();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getBrokerAccountStatus();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getBrokerAccountStatusReason();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getType();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getSubType();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getBrokerId();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getDomicile();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getAllowIlliquidInvestments();
  if (f) {
    writer.writeBool(
      10,
      f
    );
  }
  f = message.getAccountLegalName();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getAccreditation();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
  f = message.getPrimaryApplicationSignedOn();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      google_type_date_pb.Date.serializeBinaryToWriter
    );
  }
  f = message.getClearingInformation();
  if (f.length > 0) {
    writer.writeString(
      14,
      f
    );
  }
  f = message.getDvpExemptions();
  if (f.length > 0) {
    writer.writeString(
      15,
      f
    );
  }
  f = message.getDinoMigrationAccount();
  if (f) {
    writer.writeBool(
      16,
      f
    );
  }
  f = message.getMigrationChanges();
  if (f.length > 0) {
    writer.writeString(
      17,
      f
    );
  }
  f = message.getCurrentUserIsPrimary();
  if (f) {
    writer.writeBool(
      18,
      f
    );
  }
  f = message.getOwnerId();
  if (f.length > 0) {
    writer.writeString(
      19,
      f
    );
  }
  f = message.getFirstName();
  if (f.length > 0) {
    writer.writeString(
      20,
      f
    );
  }
  f = message.getMiddleName();
  if (f.length > 0) {
    writer.writeString(
      21,
      f
    );
  }
  f = message.getEmail();
  if (f.length > 0) {
    writer.writeString(
      22,
      f
    );
  }
  f = message.getLastName();
  if (f.length > 0) {
    writer.writeString(
      23,
      f
    );
  }
  f = message.getBirthDate();
  if (f != null) {
    writer.writeMessage(
      24,
      f,
      google_type_date_pb.Date.serializeBinaryToWriter
    );
  }
  f = message.getCitizenshipCountryCode();
  if (f.length > 0) {
    writer.writeString(
      25,
      f
    );
  }
  f = message.getCountryCode();
  if (f.length > 0) {
    writer.writeString(
      26,
      f
    );
  }
  f = message.getTin();
  if (f.length > 0) {
    writer.writeString(
      27,
      f
    );
  }
  f = message.getInternationalTin();
  if (f.length > 0) {
    writer.writeString(
      28,
      f
    );
  }
  f = message.getTinCountryCode();
  if (f.length > 0) {
    writer.writeString(
      29,
      f
    );
  }
  f = message.getPhysicalStreet();
  if (f.length > 0) {
    writer.writeString(
      30,
      f
    );
  }
  f = message.getPhysicalStreet2();
  if (f.length > 0) {
    writer.writeString(
      31,
      f
    );
  }
  f = message.getPhysicalStreet3();
  if (f.length > 0) {
    writer.writeString(
      32,
      f
    );
  }
  f = message.getPhysicalStreet4();
  if (f.length > 0) {
    writer.writeString(
      33,
      f
    );
  }
  f = message.getPhysicalCity();
  if (f.length > 0) {
    writer.writeString(
      34,
      f
    );
  }
  f = message.getPhysicalRegion();
  if (f.length > 0) {
    writer.writeString(
      35,
      f
    );
  }
  f = message.getPhysicalPostalCode();
  if (f.length > 0) {
    writer.writeString(
      36,
      f
    );
  }
  f = message.getPhysicalCountryCode();
  if (f.length > 0) {
    writer.writeString(
      37,
      f
    );
  }
  f = message.getMailingStreet();
  if (f.length > 0) {
    writer.writeString(
      38,
      f
    );
  }
  f = message.getMailingStreet2();
  if (f.length > 0) {
    writer.writeString(
      39,
      f
    );
  }
  f = message.getMailingStreet3();
  if (f.length > 0) {
    writer.writeString(
      40,
      f
    );
  }
  f = message.getMailingStreet4();
  if (f.length > 0) {
    writer.writeString(
      41,
      f
    );
  }
  f = message.getMailingCity();
  if (f.length > 0) {
    writer.writeString(
      42,
      f
    );
  }
  f = message.getMailingRegion();
  if (f.length > 0) {
    writer.writeString(
      43,
      f
    );
  }
  f = message.getMailingPostalCode();
  if (f.length > 0) {
    writer.writeString(
      44,
      f
    );
  }
  f = message.getMailingCountryCode();
  if (f.length > 0) {
    writer.writeString(
      45,
      f
    );
  }
  f = message.getEmploymentStatusId();
  if (f.length > 0) {
    writer.writeString(
      46,
      f
    );
  }
  f = message.getEmploymentStatusLabel();
  if (f.length > 0) {
    writer.writeString(
      47,
      f
    );
  }
  f = message.getEmploymentEmployerName();
  if (f.length > 0) {
    writer.writeString(
      48,
      f
    );
  }
  f = message.getEmploymentOccupation();
  if (f.length > 0) {
    writer.writeString(
      49,
      f
    );
  }
  f = message.getInvestorPurposeId();
  if (f.length > 0) {
    writer.writeString(
      50,
      f
    );
  }
  f = message.getInvestorPurposeLabel();
  if (f.length > 0) {
    writer.writeString(
      51,
      f
    );
  }
  f = message.getInvestmentAllowIlliquidInvestments();
  if (f) {
    writer.writeBool(
      52,
      f
    );
  }
  f = message.getHasPublicDisclosure();
  if (f) {
    writer.writeBool(
      53,
      f
    );
  }
  f = message.getPublicDisclosure();
  if (f.length > 0) {
    writer.writeString(
      54,
      f
    );
  }
  f = message.getHasStockDisclosure();
  if (f) {
    writer.writeBool(
      55,
      f
    );
  }
  f = message.getStockDisclosureFirm();
  if (f.length > 0) {
    writer.writeString(
      56,
      f
    );
  }
  f = message.getStockDisclosurePosition();
  if (f.length > 0) {
    writer.writeString(
      57,
      f
    );
  }
  f = message.getCustomerAgreementsWebTermCondition();
  if (f != null) {
    writer.writeMessage(
      58,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getCustomerAgreementsDisclosureStatement();
  if (f != null) {
    writer.writeMessage(
      59,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getCustomerAgreementsFeeSchedule();
  if (f != null) {
    writer.writeMessage(
      60,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getTrustedContactFirstName();
  if (f.length > 0) {
    writer.writeString(
      61,
      f
    );
  }
  f = message.getTrustedContactLastName();
  if (f.length > 0) {
    writer.writeString(
      62,
      f
    );
  }
  f = message.getTrustedContactEmailAddress();
  if (f.length > 0) {
    writer.writeString(
      63,
      f
    );
  }
  f = message.getTrustedContactPhoneNumber();
  if (f.length > 0) {
    writer.writeString(
      64,
      f
    );
  }
  f = message.getTrustedContactAddressLine1();
  if (f.length > 0) {
    writer.writeString(
      65,
      f
    );
  }
  f = message.getTrustedContactAddressLine2();
  if (f.length > 0) {
    writer.writeString(
      66,
      f
    );
  }
  f = message.getTrustedContactCity();
  if (f.length > 0) {
    writer.writeString(
      67,
      f
    );
  }
  f = message.getTrustedContactRegion();
  if (f.length > 0) {
    writer.writeString(
      68,
      f
    );
  }
  f = message.getTrustedContactPostalCode();
  if (f.length > 0) {
    writer.writeString(
      69,
      f
    );
  }
  f = message.getTrustedContactCountry();
  if (f.length > 0) {
    writer.writeString(
      70,
      f
    );
  }
  f = message.getTrustedContactOptOut();
  if (f) {
    writer.writeBool(
      71,
      f
    );
  }
};


/**
 * optional uint32 client_id = 1;
 * @return {number}
 */
proto.apipb.ApiClient.prototype.getClientId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setClientId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string id = 2;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string kyc_status = 3;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getKycStatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setKycStatus = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string broker_account_status = 4;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getBrokerAccountStatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setBrokerAccountStatus = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string broker_account_status_reason = 5;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getBrokerAccountStatusReason = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setBrokerAccountStatusReason = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string type = 6;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setType = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string sub_type = 7;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getSubType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setSubType = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string broker_id = 8;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getBrokerId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setBrokerId = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string domicile = 9;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getDomicile = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setDomicile = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional bool allow_illiquid_investments = 10;
 * @return {boolean}
 */
proto.apipb.ApiClient.prototype.getAllowIlliquidInvestments = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 10, false));
};


/**
 * @param {boolean} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setAllowIlliquidInvestments = function(value) {
  return jspb.Message.setProto3BooleanField(this, 10, value);
};


/**
 * optional string account_legal_name = 11;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getAccountLegalName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setAccountLegalName = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional string accreditation = 12;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getAccreditation = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setAccreditation = function(value) {
  return jspb.Message.setProto3StringField(this, 12, value);
};


/**
 * optional google.type.Date primary_application_signed_on = 13;
 * @return {?proto.google.type.Date}
 */
proto.apipb.ApiClient.prototype.getPrimaryApplicationSignedOn = function() {
  return /** @type{?proto.google.type.Date} */ (
    jspb.Message.getWrapperField(this, google_type_date_pb.Date, 13));
};


/**
 * @param {?proto.google.type.Date|undefined} value
 * @return {!proto.apipb.ApiClient} returns this
*/
proto.apipb.ApiClient.prototype.setPrimaryApplicationSignedOn = function(value) {
  return jspb.Message.setWrapperField(this, 13, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.clearPrimaryApplicationSignedOn = function() {
  return this.setPrimaryApplicationSignedOn(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apipb.ApiClient.prototype.hasPrimaryApplicationSignedOn = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional string clearing_information = 14;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getClearingInformation = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setClearingInformation = function(value) {
  return jspb.Message.setProto3StringField(this, 14, value);
};


/**
 * optional string dvp_exemptions = 15;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getDvpExemptions = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 15, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setDvpExemptions = function(value) {
  return jspb.Message.setProto3StringField(this, 15, value);
};


/**
 * optional bool dino_migration_account = 16;
 * @return {boolean}
 */
proto.apipb.ApiClient.prototype.getDinoMigrationAccount = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 16, false));
};


/**
 * @param {boolean} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setDinoMigrationAccount = function(value) {
  return jspb.Message.setProto3BooleanField(this, 16, value);
};


/**
 * optional string migration_changes = 17;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getMigrationChanges = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 17, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setMigrationChanges = function(value) {
  return jspb.Message.setProto3StringField(this, 17, value);
};


/**
 * optional bool current_user_is_primary = 18;
 * @return {boolean}
 */
proto.apipb.ApiClient.prototype.getCurrentUserIsPrimary = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 18, false));
};


/**
 * @param {boolean} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setCurrentUserIsPrimary = function(value) {
  return jspb.Message.setProto3BooleanField(this, 18, value);
};


/**
 * optional string owner_id = 19;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getOwnerId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 19, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setOwnerId = function(value) {
  return jspb.Message.setProto3StringField(this, 19, value);
};


/**
 * optional string first_name = 20;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getFirstName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 20, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setFirstName = function(value) {
  return jspb.Message.setProto3StringField(this, 20, value);
};


/**
 * optional string middle_name = 21;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getMiddleName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 21, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setMiddleName = function(value) {
  return jspb.Message.setProto3StringField(this, 21, value);
};


/**
 * optional string email = 22;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 22, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setEmail = function(value) {
  return jspb.Message.setProto3StringField(this, 22, value);
};


/**
 * optional string last_name = 23;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getLastName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 23, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setLastName = function(value) {
  return jspb.Message.setProto3StringField(this, 23, value);
};


/**
 * optional google.type.Date birth_date = 24;
 * @return {?proto.google.type.Date}
 */
proto.apipb.ApiClient.prototype.getBirthDate = function() {
  return /** @type{?proto.google.type.Date} */ (
    jspb.Message.getWrapperField(this, google_type_date_pb.Date, 24));
};


/**
 * @param {?proto.google.type.Date|undefined} value
 * @return {!proto.apipb.ApiClient} returns this
*/
proto.apipb.ApiClient.prototype.setBirthDate = function(value) {
  return jspb.Message.setWrapperField(this, 24, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.clearBirthDate = function() {
  return this.setBirthDate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apipb.ApiClient.prototype.hasBirthDate = function() {
  return jspb.Message.getField(this, 24) != null;
};


/**
 * optional string citizenship_country_code = 25;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getCitizenshipCountryCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 25, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setCitizenshipCountryCode = function(value) {
  return jspb.Message.setProto3StringField(this, 25, value);
};


/**
 * optional string country_code = 26;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getCountryCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 26, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setCountryCode = function(value) {
  return jspb.Message.setProto3StringField(this, 26, value);
};


/**
 * optional string tin = 27;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getTin = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 27, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setTin = function(value) {
  return jspb.Message.setProto3StringField(this, 27, value);
};


/**
 * optional string international_tin = 28;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getInternationalTin = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 28, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setInternationalTin = function(value) {
  return jspb.Message.setProto3StringField(this, 28, value);
};


/**
 * optional string tin_country_code = 29;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getTinCountryCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 29, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setTinCountryCode = function(value) {
  return jspb.Message.setProto3StringField(this, 29, value);
};


/**
 * optional string physical_street = 30;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getPhysicalStreet = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 30, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setPhysicalStreet = function(value) {
  return jspb.Message.setProto3StringField(this, 30, value);
};


/**
 * optional string physical_street2 = 31;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getPhysicalStreet2 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 31, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setPhysicalStreet2 = function(value) {
  return jspb.Message.setProto3StringField(this, 31, value);
};


/**
 * optional string physical_street3 = 32;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getPhysicalStreet3 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 32, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setPhysicalStreet3 = function(value) {
  return jspb.Message.setProto3StringField(this, 32, value);
};


/**
 * optional string physical_street4 = 33;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getPhysicalStreet4 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 33, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setPhysicalStreet4 = function(value) {
  return jspb.Message.setProto3StringField(this, 33, value);
};


/**
 * optional string physical_city = 34;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getPhysicalCity = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 34, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setPhysicalCity = function(value) {
  return jspb.Message.setProto3StringField(this, 34, value);
};


/**
 * optional string physical_region = 35;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getPhysicalRegion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 35, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setPhysicalRegion = function(value) {
  return jspb.Message.setProto3StringField(this, 35, value);
};


/**
 * optional string physical_postal_code = 36;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getPhysicalPostalCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 36, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setPhysicalPostalCode = function(value) {
  return jspb.Message.setProto3StringField(this, 36, value);
};


/**
 * optional string physical_country_code = 37;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getPhysicalCountryCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 37, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setPhysicalCountryCode = function(value) {
  return jspb.Message.setProto3StringField(this, 37, value);
};


/**
 * optional string mailing_street = 38;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getMailingStreet = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 38, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setMailingStreet = function(value) {
  return jspb.Message.setProto3StringField(this, 38, value);
};


/**
 * optional string mailing_street2 = 39;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getMailingStreet2 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 39, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setMailingStreet2 = function(value) {
  return jspb.Message.setProto3StringField(this, 39, value);
};


/**
 * optional string mailing_street3 = 40;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getMailingStreet3 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 40, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setMailingStreet3 = function(value) {
  return jspb.Message.setProto3StringField(this, 40, value);
};


/**
 * optional string mailing_street4 = 41;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getMailingStreet4 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 41, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setMailingStreet4 = function(value) {
  return jspb.Message.setProto3StringField(this, 41, value);
};


/**
 * optional string mailing_city = 42;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getMailingCity = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 42, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setMailingCity = function(value) {
  return jspb.Message.setProto3StringField(this, 42, value);
};


/**
 * optional string mailing_region = 43;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getMailingRegion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 43, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setMailingRegion = function(value) {
  return jspb.Message.setProto3StringField(this, 43, value);
};


/**
 * optional string mailing_postal_code = 44;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getMailingPostalCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 44, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setMailingPostalCode = function(value) {
  return jspb.Message.setProto3StringField(this, 44, value);
};


/**
 * optional string mailing_country_code = 45;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getMailingCountryCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 45, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setMailingCountryCode = function(value) {
  return jspb.Message.setProto3StringField(this, 45, value);
};


/**
 * optional string employment_status_id = 46;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getEmploymentStatusId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 46, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setEmploymentStatusId = function(value) {
  return jspb.Message.setProto3StringField(this, 46, value);
};


/**
 * optional string employment_status_label = 47;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getEmploymentStatusLabel = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 47, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setEmploymentStatusLabel = function(value) {
  return jspb.Message.setProto3StringField(this, 47, value);
};


/**
 * optional string employment_employer_name = 48;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getEmploymentEmployerName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 48, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setEmploymentEmployerName = function(value) {
  return jspb.Message.setProto3StringField(this, 48, value);
};


/**
 * optional string employment_occupation = 49;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getEmploymentOccupation = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 49, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setEmploymentOccupation = function(value) {
  return jspb.Message.setProto3StringField(this, 49, value);
};


/**
 * optional string investor_purpose_id = 50;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getInvestorPurposeId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 50, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setInvestorPurposeId = function(value) {
  return jspb.Message.setProto3StringField(this, 50, value);
};


/**
 * optional string investor_purpose_label = 51;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getInvestorPurposeLabel = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 51, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setInvestorPurposeLabel = function(value) {
  return jspb.Message.setProto3StringField(this, 51, value);
};


/**
 * optional bool investment_allow_illiquid_investments = 52;
 * @return {boolean}
 */
proto.apipb.ApiClient.prototype.getInvestmentAllowIlliquidInvestments = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 52, false));
};


/**
 * @param {boolean} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setInvestmentAllowIlliquidInvestments = function(value) {
  return jspb.Message.setProto3BooleanField(this, 52, value);
};


/**
 * optional bool has_public_disclosure = 53;
 * @return {boolean}
 */
proto.apipb.ApiClient.prototype.getHasPublicDisclosure = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 53, false));
};


/**
 * @param {boolean} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setHasPublicDisclosure = function(value) {
  return jspb.Message.setProto3BooleanField(this, 53, value);
};


/**
 * optional string public_disclosure = 54;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getPublicDisclosure = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 54, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setPublicDisclosure = function(value) {
  return jspb.Message.setProto3StringField(this, 54, value);
};


/**
 * optional bool has_stock_disclosure = 55;
 * @return {boolean}
 */
proto.apipb.ApiClient.prototype.getHasStockDisclosure = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 55, false));
};


/**
 * @param {boolean} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setHasStockDisclosure = function(value) {
  return jspb.Message.setProto3BooleanField(this, 55, value);
};


/**
 * optional string stock_disclosure_firm = 56;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getStockDisclosureFirm = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 56, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setStockDisclosureFirm = function(value) {
  return jspb.Message.setProto3StringField(this, 56, value);
};


/**
 * optional string stock_disclosure_position = 57;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getStockDisclosurePosition = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 57, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setStockDisclosurePosition = function(value) {
  return jspb.Message.setProto3StringField(this, 57, value);
};


/**
 * optional google.protobuf.Timestamp customer_agreements_web_term_condition = 58;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.apipb.ApiClient.prototype.getCustomerAgreementsWebTermCondition = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 58));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.apipb.ApiClient} returns this
*/
proto.apipb.ApiClient.prototype.setCustomerAgreementsWebTermCondition = function(value) {
  return jspb.Message.setWrapperField(this, 58, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.clearCustomerAgreementsWebTermCondition = function() {
  return this.setCustomerAgreementsWebTermCondition(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apipb.ApiClient.prototype.hasCustomerAgreementsWebTermCondition = function() {
  return jspb.Message.getField(this, 58) != null;
};


/**
 * optional google.protobuf.Timestamp customer_agreements_disclosure_statement = 59;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.apipb.ApiClient.prototype.getCustomerAgreementsDisclosureStatement = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 59));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.apipb.ApiClient} returns this
*/
proto.apipb.ApiClient.prototype.setCustomerAgreementsDisclosureStatement = function(value) {
  return jspb.Message.setWrapperField(this, 59, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.clearCustomerAgreementsDisclosureStatement = function() {
  return this.setCustomerAgreementsDisclosureStatement(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apipb.ApiClient.prototype.hasCustomerAgreementsDisclosureStatement = function() {
  return jspb.Message.getField(this, 59) != null;
};


/**
 * optional google.protobuf.Timestamp customer_agreements_fee_schedule = 60;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.apipb.ApiClient.prototype.getCustomerAgreementsFeeSchedule = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 60));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.apipb.ApiClient} returns this
*/
proto.apipb.ApiClient.prototype.setCustomerAgreementsFeeSchedule = function(value) {
  return jspb.Message.setWrapperField(this, 60, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.clearCustomerAgreementsFeeSchedule = function() {
  return this.setCustomerAgreementsFeeSchedule(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apipb.ApiClient.prototype.hasCustomerAgreementsFeeSchedule = function() {
  return jspb.Message.getField(this, 60) != null;
};


/**
 * optional string trusted_contact_first_name = 61;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getTrustedContactFirstName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 61, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setTrustedContactFirstName = function(value) {
  return jspb.Message.setProto3StringField(this, 61, value);
};


/**
 * optional string trusted_contact_last_name = 62;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getTrustedContactLastName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 62, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setTrustedContactLastName = function(value) {
  return jspb.Message.setProto3StringField(this, 62, value);
};


/**
 * optional string trusted_contact_email_address = 63;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getTrustedContactEmailAddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 63, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setTrustedContactEmailAddress = function(value) {
  return jspb.Message.setProto3StringField(this, 63, value);
};


/**
 * optional string trusted_contact_phone_number = 64;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getTrustedContactPhoneNumber = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 64, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setTrustedContactPhoneNumber = function(value) {
  return jspb.Message.setProto3StringField(this, 64, value);
};


/**
 * optional string trusted_contact_address_line1 = 65;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getTrustedContactAddressLine1 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 65, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setTrustedContactAddressLine1 = function(value) {
  return jspb.Message.setProto3StringField(this, 65, value);
};


/**
 * optional string trusted_contact_address_line2 = 66;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getTrustedContactAddressLine2 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 66, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setTrustedContactAddressLine2 = function(value) {
  return jspb.Message.setProto3StringField(this, 66, value);
};


/**
 * optional string trusted_contact_city = 67;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getTrustedContactCity = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 67, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setTrustedContactCity = function(value) {
  return jspb.Message.setProto3StringField(this, 67, value);
};


/**
 * optional string trusted_contact_region = 68;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getTrustedContactRegion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 68, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setTrustedContactRegion = function(value) {
  return jspb.Message.setProto3StringField(this, 68, value);
};


/**
 * optional string trusted_contact_postal_code = 69;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getTrustedContactPostalCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 69, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setTrustedContactPostalCode = function(value) {
  return jspb.Message.setProto3StringField(this, 69, value);
};


/**
 * optional string trusted_contact_country = 70;
 * @return {string}
 */
proto.apipb.ApiClient.prototype.getTrustedContactCountry = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 70, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setTrustedContactCountry = function(value) {
  return jspb.Message.setProto3StringField(this, 70, value);
};


/**
 * optional bool trusted_contact_opt_out = 71;
 * @return {boolean}
 */
proto.apipb.ApiClient.prototype.getTrustedContactOptOut = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 71, false));
};


/**
 * @param {boolean} value
 * @return {!proto.apipb.ApiClient} returns this
 */
proto.apipb.ApiClient.prototype.setTrustedContactOptOut = function(value) {
  return jspb.Message.setProto3BooleanField(this, 71, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.apipb.ListApiClientRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.apipb.ListApiClientRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.apipb.ListApiClientRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apipb.ListApiClientRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    brokerId: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.apipb.ListApiClientRequest}
 */
proto.apipb.ListApiClientRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.apipb.ListApiClientRequest;
  return proto.apipb.ListApiClientRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.apipb.ListApiClientRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.apipb.ListApiClientRequest}
 */
proto.apipb.ListApiClientRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setBrokerId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.apipb.ListApiClientRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.apipb.ListApiClientRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.apipb.ListApiClientRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apipb.ListApiClientRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBrokerId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string broker_id = 1;
 * @return {string}
 */
proto.apipb.ListApiClientRequest.prototype.getBrokerId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.apipb.ListApiClientRequest} returns this
 */
proto.apipb.ListApiClientRequest.prototype.setBrokerId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.apipb.ListApiClientResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.apipb.ListApiClientResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.apipb.ListApiClientResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.apipb.ListApiClientResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apipb.ListApiClientResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    apiClientsList: jspb.Message.toObjectList(msg.getApiClientsList(),
    proto.apipb.ApiClient.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.apipb.ListApiClientResponse}
 */
proto.apipb.ListApiClientResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.apipb.ListApiClientResponse;
  return proto.apipb.ListApiClientResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.apipb.ListApiClientResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.apipb.ListApiClientResponse}
 */
proto.apipb.ListApiClientResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.apipb.ApiClient;
      reader.readMessage(value,proto.apipb.ApiClient.deserializeBinaryFromReader);
      msg.addApiClients(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.apipb.ListApiClientResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.apipb.ListApiClientResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.apipb.ListApiClientResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apipb.ListApiClientResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getApiClientsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.apipb.ApiClient.serializeBinaryToWriter
    );
  }
};


/**
 * repeated ApiClient api_clients = 1;
 * @return {!Array<!proto.apipb.ApiClient>}
 */
proto.apipb.ListApiClientResponse.prototype.getApiClientsList = function() {
  return /** @type{!Array<!proto.apipb.ApiClient>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.apipb.ApiClient, 1));
};


/**
 * @param {!Array<!proto.apipb.ApiClient>} value
 * @return {!proto.apipb.ListApiClientResponse} returns this
*/
proto.apipb.ListApiClientResponse.prototype.setApiClientsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.apipb.ApiClient=} opt_value
 * @param {number=} opt_index
 * @return {!proto.apipb.ApiClient}
 */
proto.apipb.ListApiClientResponse.prototype.addApiClients = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.apipb.ApiClient, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.apipb.ListApiClientResponse} returns this
 */
proto.apipb.ListApiClientResponse.prototype.clearApiClientsList = function() {
  return this.setApiClientsList([]);
};


goog.object.extend(exports, proto.apipb);
