export const menus = [
  {
    id: 1,
    groupLabel: 'Admin / Account Setup',
    label: 'User',
    link: '/app/account-setup/user',
    page: 'user',
  },
  {
    id: 1.2,
    groupLabel: 'Admin / Account Setup',
    label: 'Access',
    link: '/app/account-setup/access',
    page: 'access',
  },
  {
    id: 2,
    groupLabel: 'Admin / Account Setup',
    label: 'Client Account',
    link: '/app/account-setup/client-account',
    page: 'client-account',
  },
  {
    id: 3,
    groupLabel: 'Admin / Account Setup',
    label: 'GL Account',
    link: '/app/account-setup/gl-account',
    page: 'gl-account',
  },
  {
    id: 4,
    groupLabel: 'Balance / Bank',
    label: 'Bank Account',
    link: '/app/bank/bank-account',
    page: 'bank-account',
  },
  {
    id: 5,
    groupLabel: 'Balance / Bank',
    label: 'Bank Address',
    link: '/app/bank/bank-address',
    page: 'bank-address',
  },
  {
    id: 5.1,
    groupLabel: 'Balance / Bank',
    label: 'Wallet',
    link: '/app/bank/wallet',
    page: 'wallet',
  },
  {
    id: 6,
    groupLabel: 'Admin / Misc',
    label: 'Margin Interest Rate',
    link: '/app/misc/margin-interest-rate',
    page: 'margin-interest-rate',
  },
  {
    id: 7,
    groupLabel: 'Admin / Misc',
    label: 'Recon Mapping',
    link: '/app/misc/recon-mapping',
    page: 'recon-mapping',
  },
  {
    id: 7.1,
    groupLabel: 'Admin / Misc',
    label: 'Tax Rate',
    link: '/app/misc/tax-rate',
    page: 'tax-rate',
  },
  {
    id: 7.2,
    groupLabel: 'Admin / Misc',
    label: 'Credential',
    link: '/app/misc/credential',
    page: 'credential',
  },
  {
    id: 7.3,
    groupLabel: 'Admin / Misc',
    label: 'Commission',
    link: '/app/misc/commission',
    page: 'commission',
  },
  {
    id: 9,
    groupLabel: 'Admin / System Profile',
    label: 'System Profile',
    link: '/app/system-profile/system-profile',
    page: 'system-profile',
  },
  {
    id: 10,
    groupLabel: 'Admin / System Profile',
    label: 'System Code',
    link: '/app/system-profile/system-code',
    page: 'system-code',
  },
  {
    id: 11,
    groupLabel: 'Admin / System Profile',
    label: 'System Number',
    link: '/app/system-profile/system-number',
    page: 'system-number',
  },
  {
    id: 11.1,
    groupLabel: 'Admin / System Profile',
    label: 'System Process',
    link: '/app/system-profile/system-process',
    page: 'system-process',
  },
  {
    id: 12,
    groupLabel: 'Admin / System Profile',
    label: 'Calendar',
    link: '/app/system-profile/calendar',
    page: 'calendar',
  },
  {
    id: 12.1,
    groupLabel: 'Admin / System Profile',
    label: 'File Path',
    link: '/app/system-profile/file-path',
    page: 'file-path',
  },
  {
    id: 13,
    groupLabel: 'Email Manager / Email Manager',
    label: 'Email Manager',
    link: '/app/email-manager/email-manager',
    page: 'email-manager',
  },
  {
    id: 13.1,
    groupLabel: 'Email Manager / Email Sender',
    label: 'Email Sender',
    link: '/app/email-manager/email-sender',
    page: 'email-sender',
  },
  {
    id: 14,
    groupLabel: 'Security / Security Details',
    label: 'Price',
    link: '/app/security-details/price',
    page: 'price',
  },
  {
    id: 15,
    groupLabel: 'Admin / Security Details',
    label: 'Master Profile',
    link: '/app/security-details/master-profile',
    page: 'master-profile',
  },
  {
    id: 15.1,
    groupLabel: 'Admin / Integration',
    label: 'Fix Tag Setup',
    link: '/app/integration/fix-tag-setup',
    page: 'fix-tag-setup',
  },
  {
    id: 15.2,
    groupLabel: 'Admin / Integration',
    label: 'Fix Value',
    link: '/app/integration/fix-value',
    page: 'fix-value',
  },
  {
    id: 15.3,
    groupLabel: 'Admin / Integration',
    label: 'API Value',
    link: '/app/integration/api-value',
    page: 'api-value',
  },
  {
    id: 15.4,
    groupLabel: 'Admin / User Guide',
    label: 'User Guide',
    link: '/app/system-profile/user-guide',
    page: 'user-guide',
  },
  {
    id: 15.5,
    groupLabel: 'Admin / User Guide',
    label: 'Data Dictionary',
    link: '/app/user-guide/data-dictionary',
    page: 'data-dictionary',
  },
  {
    id: 15.6,
    groupLabel: 'Admin / User Guide',
    label: 'Question and Answer',
    link: '/app/user-guide/question-and-answer',
    page: 'faqs',
  },
  // {
  // id: 15,
  // groupLabel: 'Admin / Security Details',
  // label: 'Equity',
  // link: '/app/security-details/equity',
  // page: 'equity',
  // },
  {
    id: 16,
    groupLabel: 'Security / Security Details',
    label: 'Option Profile',
    link: '/app/security-details/option-profile',
    page: 'option-profile',
  },
  // {
  // id: ,
  // groupLabel: 'Security / Security Details',
  // label: 'Etf',
  // link: '/app/security-details/etf',
  // page: 'etf',
  // },
  // {
  // id: ,
  // groupLabel: 'Security / Security Details',
  // label: 'SLL',
  // link: '/app/security-details/sll',
  // page: 'sll',
  // },
  {
    id: 17,
    groupLabel: 'Balance / Cash',
    label: 'Balance',
    link: '/app/cash/balance',
    page: 'balance',
  },
  // {
  // id: 18,
  // groupLabel: 'Balance / Cash',
  // label: 'Balance Reconciliation',
  // link: '/app/cash/reconciliation-balance',
  // page: 'reconciliation-balance',
  // },
  {
    id: 18,
    groupLabel: 'Balance / Cash',
    label: 'Trial Balance',
    link: '/app/cash/trial-balance',
    page: 'trial-balance',
  },
  {
    id: 19,
    groupLabel: 'Balance / Cash',
    label: 'GL Report',
    link: '/app/cash/gl-report',
    page: 'gl-report',
  },
  {
    id: 20,
    groupLabel: 'Balance / Bank',
    label: 'ACH/Wire',
    link: '/app/bank/ach-wire',
    page: 'ach-wire',
  },
  {
    id: 20.1,
    groupLabel: 'Balance / Bank',
    label: 'Digital Bank Request',
    link: '/app/bank/digital-bank-request',
    page: 'digital-bank-request',
  },
  {
    id: 20.2,
    groupLabel: 'Balance / Bank',
    label: 'Bank Balance',
    link: '/app/bank/bank-balance',
    page: 'bank-balance',
  },
  {
    id: 20.3,
    groupLabel: 'Balance / Bank',
    label: 'Bank Recon',
    link: '/app/bank/bank-recon',
    page: 'bank-recon',
  },
  {
    id: 21,
    groupLabel: 'Balance / Cash',
    label: 'Balance Summary',
    link: '/app/cash/balance-summary-report',
    page: 'balance-summary-report',
  },
  {
    id: 22,
    groupLabel: 'Balance / Fee',
    label: 'Reg Fee',
    link: '/app/fee/reg-fee',
    page: 'reg-fee',
  },
  {
    id: 23,
    groupLabel: 'Balance / Fee',
    label: 'Taf Fee',
    link: '/app/fee/taf-fee',
    page: 'taf-fee',
  },
  {
    id: 24,
    groupLabel: 'Balance / Fee',
    label: 'Margin Interest Calc',
    link: '/app/fee/margin-interest-calc',
    page: 'margin-interest-calc',
  },
  {
    id: 24.1,
    groupLabel: 'Balance / Security Details',
    label: 'Security Margin Rate',
    link: '/app/security-details/security-margin-rate',
    page: 'security-margin-rate',
  },
  {
    id: 25,
    groupLabel: 'Compliance / BlueSheet',
    label: 'BlueSheet',
    link: '/app/bluesheet/bluesheet',
    page: 'bluesheet',
  },
  {
    id: 26,
    groupLabel: 'Compliance / BlueSheet',
    label: 'Large Trader ID',
    link: '/app/bluesheet/large-trader-id',
    page: 'large-trader-id',
  },
  {
    id: 27,
    groupLabel: 'Compliance / CAT',
    label: 'Process Status',
    link: '/app/cat/process-status',
    page: 'process-status',
  },
  {
    id: 28,
    groupLabel: 'Compliance / Regulatory',
    label: '15c3',
    link: '/app/regulatory/15c3',
    page: '15c3',
  },
  {
    id: 29,
    groupLabel: 'Compliance / Regulatory',
    label: 'Monthly Report',
    link: '/app/regulatory/monthly-report',
    page: 'monthly-report',
  },
  {
    id: 30,
    groupLabel: 'Compliance / Regulatory',
    label: 'Quarterly Report',
    link: '/app/regulatory/quarterly-report',
    page: 'quarterly-report',
  },
  {
    id: 31,
    groupLabel: 'Compliance / Risk Manager',
    label: 'Call Logs',
    link: '/app/risk-manager/call-logs',
    page: 'call-logs',
  },
  {
    id: 32,
    groupLabel: 'Compliance / Risk Manager',
    label: 'Buying Power',
    link: '/app/risk-manager/buying-power',
    page: 'buying-power',
  },
  // {
  // id: 32,
  // groupLabel: 'Compliance / Risk Manager',
  // label: 'Day Trade Buying Power Used',
  // link: '/app/risk-manager/day-trade-buying-power-used',
  // page: 'day-trade-buying-power-used',
  // },
  {
    id: 33,
    groupLabel: 'Compliance / Risk Manager',
    label: 'Margin Requirement',
    link: '/app/risk-manager/margin-requirement',
    page: 'margin-requirement',
  },
  {
    id: 34,
    groupLabel: 'Compliance / Segregation',
    label: 'Segregation',
    link: '/app/segregation/segregation',
    page: 'segregation',
  },
  // {
  // id: 32,
  // groupLabel: 'Compliance / Segregation',
  // label: 'Per Symbol',
  // // link: '/app/segregation/segregation',
  // // page: 'segregation',
  // },
  {
    id: 35,
    groupLabel: 'Compliance / Segregation',
    label: 'Priority',
    link: '/app/segregation/priority',
    page: 'priority',
  },
  // {
  // id: 34,
  // groupLabel: 'Compliance / Segregation',
  // label: 'Segregation',
  // link: '/app/segregation/segregation',
  // page: 'segregation',
  // },
  // {
  // id: 35,
  // groupLabel: 'Compliance / Calculation',
  // label: 'Reserve Calc',
  // link: '/app/calculation/reserve-calc',
  // page: 'reserve-calc',
  // },
  {
    id: 36,
    groupLabel: 'Position / Position',
    label: 'Position',
    link: '/app/position/position',
    page: 'position',
  },
  {
    id: 37,
    groupLabel: 'Position / Position',
    label: 'FINRA Short Position',
    link: '/app/position/finra-short-position',
    page: 'finra-short-position',
  },
  {
    id: 37.1,
    groupLabel: 'Position / Position',
    label: 'Stock Record',
    link: '/app/position/stock-record',
    page: 'stock-record',
  },
  {
    id: 37.2,
    groupLabel: 'Position / Position',
    label: 'Option',
    link: '/app/position/option',
    page: 'option',
  },
  {
    id: 38,
    groupLabel: 'Position / Stock Borrow',
    label: 'Stock Borrow Report',
    link: '/app/stock-borrow/report',
    page: 'report',
  },
  {
    id: 38.1,
    groupLabel: 'Position / Stock Borrow',
    label: 'Stock Borrow Rate',
    link: '/app/stock-borrow/rate',
    page: 'rate',
  },
  {
    id: 38.2,
    groupLabel: 'Position / Stock Borrow',
    label: 'Charge',
    link: '/app/stock-borrow/charge',
    page: 'charge',
  },
  // {
  // id: 38,
  // groupLabel: 'Position / Position',
  // label: 'Transfer Input',
  // link: '/app/position/transfer-input',
  // page: 'transfer-input',
  // },
  {
    id: 39,
    groupLabel: 'Position / CNS',
    label: 'Account Summary',
    link: '/app/cns/account-summary',
    page: 'account-summary',
  },
  {
    id: 40,
    groupLabel: 'Position / CNS',
    label: 'CNS vs DTCC',
    link: '/app/cns/cns-vs-dtcc',
    page: 'cns-vs-dtcc',
  },
  {
    id: 41,
    groupLabel: 'Position / CNS',
    label: 'Position Aging',
    link: '/app/cns/position-aging',
    page: 'position-aging',
  },
  {
    id: 42,
    groupLabel: 'Position / CNS',
    label: 'Projection',
    link: '/app/cns/projection',
    page: 'projection',
  },
  {
    id: 43,
    groupLabel: 'Position / CNS',
    label: 'Settlement Short Position',
    link: '/app/cns/settlement-short-position',
    page: 'settlement-short-position',
  },
  {
    id: 44,
    groupLabel: 'Position / CNS',
    label: 'Trade Summary',
    link: '/app/cns/trade-summary',
    page: 'Trade-summary',
  },
  {
    id: 45,
    groupLabel: 'Position / Corp Action',
    label: 'Announcement',
    link: '/app/corp-action/announcement',
    page: 'announcement',
  },
  {
    id: 46,
    groupLabel: 'Position / Corp Action',
    label: 'Entitlement',
    link: '/app/corp-action/entitlement',
    page: 'entitlement',
  },
  // {
  // id: 45,
  // groupLabel: 'Position / Corp Action',
  // label: 'Entitlement Reconciliation',
  // link: '/app/corp-action/reconciliation-entitlement',
  // page: 'reconciliation-entitlement',
  // },
  {
    id: 47,
    groupLabel: 'Security / Corp Action',
    label: 'Corp Action Recon',
    link: '/app/corp-action/corp-action-recon',
    page: 'reconciliation-reorg',
  },
  // {
  // id: 46,
  // groupLabel: 'Security / Corp Action',
  // label: 'Corp Action Recon',
  // // link: '/app/corp-action/corp-action-recon',
  // // page: 'corp-action-recon',
  // },
  {
    id: 48,
    groupLabel: 'Position / DTCC',
    label: 'Data File Transfer',
    link: '/app/dtcc/data-file-transfer',
    page: 'data-file-transfer',
  },
  {
    id: 49,
    groupLabel: 'Position / DTCC',
    label: 'Open Item',
    link: '/app/dtcc/open-item',
    page: 'open-item',
  },
  {
    id: 50,
    groupLabel: 'Position / DTCC',
    label: 'Position',
    link: '/app/dtcc/position',
    page: 'position',
  },
  {
    id: 51,
    groupLabel: 'Position / DTCC',
    label: 'APIBAL',
    link: '/app/dtcc/apibal',
    page: 'apibal',
  },
  {
    id: 52,
    groupLabel: 'Position / DTCC',
    label: 'Received',
    link: '/app/dtcc/received',
    page: 'received',
  },
  {
    id: 53,
    groupLabel: 'Position / ACATS',
    label: 'Incoming Full',
    link: '/app/acats/full',
    page: 'full',
  },
  {
    id: 54,
    groupLabel: 'Position / ACATS',
    label: 'Incoming Partial',
    link: '/app/acats/partial',
    page: 'partial',
  },
  {
    id: 55,
    groupLabel: 'Position / ACATS',
    label: 'Outgoing Position',
    link: '/app/acats/out',
    page: 'out',
  },
  // {
  // id: 57,
  // groupLabel: 'Transacation / Position',
  // label: 'Position Reconciliation',
  // link: '/app/position/reconciliation-position',
  // page: 'reconciliation-position',
  // },
  // {
  // id: 58,
  // groupLabel: 'Transacation / Position',
  // label: 'Stock Borrow',
  // link: '/app/position/stock-borrow',
  // page: 'stock-borrow',
  // },
  {
    id: 59,
    groupLabel: 'Transaction / TRNS',
    label: 'Activity',
    link: '/app/trns/activity',
    page: 'activity',
  },
  {
    id: 60,
    groupLabel: 'Transaction / TRNS',
    label: 'Enter TRNS',
    link: '/app/trns/enter-trns',
    page: 'enter-trns',
  },
  {
    id: 61,
    groupLabel: 'Transaction / TRNS',
    label: 'NSCC',
    link: '/app/trns/nscc',
    page: 'nscc',
  },
  {
    id: 62,
    groupLabel: 'Transaction / TRNS',
    label: 'Pending TRNS',
    link: '/app/trns/pending-trns',
    page: 'pending-trns',
  },
  {
    id: 63,
    groupLabel: 'Transaction / TRNS',
    label: 'Execution Reconciliations',
    link: '/app/trns/execution-reconciliations',
    page: 'execution-reconciliations',
  },
  {
    id: 64,
    groupLabel: 'Transaction / TRNS',
    label: 'Bank Transaction',
    link: '/app/trns/bank-transaction',
    page: 'bank-transaction',
  },
  // {
  // id: 64,
  // groupLabel: 'Transaction / TRNS',
  // label: 'Fee',
  // link: '/app/trns/fee',
  // page: 'fee',
  // },
  // {
  // id: 65,
  // groupLabel: 'Transaction / TRNS',
  // label: 'Fee Management',
  // link: '/app/trns/fee-management',
  // page: 'fee-management',
  // },
  {
    id: 66,
    groupLabel: 'Transaction / Report',
    label: 'Profit and Loss',
    link: '/app/reports/profit-and-loss',
    page: 'profit-and-loss',
  },
  {
    id: 67,
    groupLabel: 'Transaction / Report',
    label: 'Monthly Statement',
    link: '/app/reports/monthly-statement',
    page: 'monthly-statement',
  },
  {
    id: 67.1,
    groupLabel: 'Admin / MISC',
    label: 'Report Template',
    link: '/app/misc/report-template',
    page: 'report-template',
  },
  {
    id: 68,
    groupLabel: 'Transaction / Report',
    label: 'Daily Trade Confirm',
    link: '/app/reports/daily-trade-confirm',
    page: 'monthly-statement',
  },
  {
    id: 68.1,
    groupLabel: 'Admin / MISC',
    label: 'Disclosure',
    link: '/app/misc/disclosure',
    page: 'disclosure',
  },
  {
    id: 69,
    groupLabel: 'Transaction / Position',
    label: 'Locate Ladder',
    link: '/app/position/locate-ladder',
    page: 'locate-ladder',
  },
  {
    id: 70,
    groupLabel: 'Position / OCC',
    label: 'Trade Recon Option',
    link: '/app/occ/option',
    page: 'trade-recon-option',
  },
  {
    id: 71,
    groupLabel: 'Position / Physical Certificate',
    label: 'Transfer Agent',
    link: '/app/physical-certificate/transfer-agent',
    page: 'transfer-agent',
  },
  {
    id: 72,
    groupLabel: 'Position / Physical Certificate',
    label: 'Physical Certificate',
    link: '/app/physical-certificate/physical-certificate',
    page: 'physical-certificate',
  },
  {
    id: 73,
    groupLabel: 'Balance / Withholding',
    label: 'Dividend',
    link: '/app/withholding/dividend',
    page: 'dividend',
  },
  {
    id: 74,
    groupLabel: 'Report / ACATS',
    label: 'Transaction',
    link: '/app/acats/multicycle',
    page: 'multicycle',
  },
  {
    id: 75,
    groupLabel: 'Report / ACATS',
    label: 'Position',
    link: '/app/acats/output-position',
    page: 'output-position',
  },
  {
    id: 75,
    groupLabel: 'Report / ACATS',
    label: 'Settlement',
    link: '/app/acats/output-settlement',
    page: 'output-settlement',
  },
  {
    id: 76,
    groupLabel: 'Surveillance / Trade Monitoring',
    label: 'Concentration',
    link: '/app/trade-monitoring/concentration',
    page: 'concentration',
  },
  {
    id: 76,
    groupLabel: 'Surveillance / Trade Monitoring',
    label: 'Undue Concentration',
    link: '/app/trade-monitoring/undue-concentration',
    page: 'undue-concentration',
  },
  {
    id: 77,
    groupLabel: 'Admin / Account Setup',
    label: 'Account Process',
    link: '/app/account-setup/account-process',
    page: 'account-process',
  },
  {
    id: 78,
    groupLabel: 'Surveillance / Surveillance',
    label: 'Surveillance Setup',
    link: '/app/surveillance/setup',
    page: 'surveillance-setup',
  },
  {
    id: 79,
    groupLabel: 'Surveillance / Surveillance',
    label: 'Surveillance Report',
    link: '/app/surveillance/report',
    page: 'surveillance-report',
  },
  {
    id: 79.1,
    groupLabel: 'Surveillance / Surveillance',
    label: 'OFAC',
    link: '/app/surveillance/ofac',
    page: 'surveillance-ofac',
  },
  {
    id: 80,
    groupLabel: 'Surveillance / Trade Monitoring',
    label: 'Parameter',
    link: '/app/trade-monitoring/parameter',
    page: 'parameter',
  },
  {
    id: 81,
    groupLabel: 'Surveillance / Trade Monitoring',
    label: 'Mini Manipulation',
    link: '/app/trade-monitoring/mini-manipulation',
    page: 'mini-manipulation',
  },
  {
    id: 82,
    groupLabel: 'Surveillance / Trade Monitoring',
    label: 'Odd Lot',
    link: '/app/trade-monitoring/odd-lot',
    page: 'odd-lot',
  },
  {
    id: 83,
    groupLabel: 'Surveillance / Trade Monitoring',
    label: 'Wash Sale',
    link: '/app/trade-monitoring/wash-sale',
    page: 'wash-sale',
  },
  {
    id: 84,
    groupLabel: 'Surveillance / Trade Monitoring',
    label: 'Average Daily Volume',
    link: '/app/trade-monitoring/average-daily-volume',
    page: 'average-daily-volume',
  },
  {
    id: 84.1,
    groupLabel: 'Surveillance / Trade Monitoring',
    label: 'Trade Participation',
    link: '/app/trade-monitoring/trade-participation',
    page: 'trade-participation',
  },
  {
    id: 84.2,
    groupLabel: 'Surveillance / Trade Monitoring',
    label: 'Layering',
    link: '/app/trade-monitoring/layering',
    page: 'layering',
  },
  {
    id: 84.3,
    groupLabel: 'Surveillance / Trade Monitoring',
    label: 'Spoofing',
    link: '/app/trade-monitoring/spoofing',
    page: 'spoofing',
  },
  {
    id: 85,
    groupLabel: 'Admin / Account Setup',
    label: 'Client Account Access',
    link: '/app/account-setup/client-account-access',
    page: 'client-account-access',
  },
  {
    id: 86,
    groupLabel: 'Transaction / Omnibus',
    label: 'ApexPro TRNS',
    link: '/app/omnibus/apexpro-trns',
    page: 'apexpro-trns',
  },
  {
    id: 87,
    groupLabel: 'Transaction / Omnibus',
    label: 'ApexPro Balance',
    link: '/app/omnibus/apexpro-balance',
    page: 'apexpro-balance',
  },
  {
    id: 88,
    groupLabel: 'Transaction / Omnibus',
    label: 'ApexPro Position',
    link: '/app/omnibus/apexpro-position',
    page: 'apexpro-position',
  },
  {
    id: 89,
    groupLabel: 'Transaction / Omnibus',
    label: 'TRNS Recon',
    link: '/app/omnibus/trns-recon',
    page: 'trns-recon',
  },
  {
    id: 90,
    groupLabel: 'Transaction / Omnibus',
    label: 'Position Reconciliation',
    link: '/app/omnibus/position-reconciliation',
    page: 'position-reconciliation',
  },
  {
    id: 91,
    groupLabel: 'Transaction / Omnibus',
    label: 'Balance Recon',
    link: '/app/omnibus/balance-reconciliation',
    page: 'balance-reconciliation',
  },
];
